ACMS-1030: Update search api and search api solr module to latest
acquia/acquia_cms pull request #1024
Opened 2022-01-07 13:05 UTC by chandan-singh7929

**Motivation**

Fixes #[ACMS-1030](https://backlog.acquia.com/browse/ACMS-1030)

**Proposed changes**

Update search api and search api solr module to latest

**Alternatives considered**

NA

**Testing steps**

- Install site with this branch
- Visit module page and verify search api and search api solr module are update.
- Enable starte module all page.

**Merge requirements**
- [_Enhancement_] _Major change_, _Minor change_, _Bug_, _Enhancement_, and/or _Chore_ label applied
- [ ] Manual testing by a reviewer

2022-01-10 11:12 UTC, nagwani commented
DO NOT MERGE

2022-01-12 08:23 UTC, vishalkhode1 requested changes
@chandan-singh7929 Please update composer.json for acquia_cms_search module.

2022-01-12 08:23 UTC, vishalkhode1 commented
> @chandan-singh7929 Please update composer.json for acquia_cms_search module.

Sorry, I didn't notice, that's already done.

2022-01-12 08:23 UTC, vishalkhode1 approved these changes

2022-01-12 08:24 UTC, merged