ACMS-1102: Upgrade drupal to 9.3.9
acquia/acquia_cms pull request #1089
Opened 2022-03-22 05:32 UTC by rajeshreeputra

**Motivation**
Fixes #[ACMS-1102](https://backlog.acquia.com/browse/ACMS-1102)

**Proposed changes**
Update Drupal core to 9.3.9

**Alternatives considered**
NA

**Testing steps**
Login to https://orionacmsdev.prod.acquia-sites.com/ as administrator
Head towards /admin/reports/updates
Verify Drupal core is updated to 9.3.9

**Merge requirements**
- [ ] _Major change_, _Minor change_, _Bug_, _Enhancement_, and/or _Chore_ label applied
- [ ] Manual testing by a reviewer

2022-03-22 07:07 UTC, vishalkhode1 requested changes
@rajeshreeputra Please update root composer.json file as well. https://github.com/acquia/acquia_cms/blob/develop/composer.json#L40

2022-03-23 16:02 UTC, vishalkhode1 requested changes

2022-03-23 16:02 UTC, vishalkhode1 commented on composer.json
> +        "drupal/core": "~9.2.15 || ~9.3.9",
@rajeshreeputra Please update drupal 9.2 version as well i.e
```suggestion
        "drupal/core": "~9.2.16 || ~9.3.9",
```

2022-03-24 03:50 UTC, rajeshreeputra commented on composer.json
> +        "drupal/core": "~9.2.15 || ~9.3.9",
Updated drupal 9.2 version

2022-03-24 15:33 UTC, merged