ACMS 1178: Allow site studio package import when we switch from profile to module
acquia/acquia_cms pull request #1136
Opened 2022-05-13 09:03 UTC by rajeshreeputra

**Motivation**
Fixes #[ACMS-1178](https://backlog.acquia.com/browse/ACMS-1178)

**Proposed changes**
Keep Site Studio package import feature intact with ACMS as module

**Alternatives considered**
NA

**Testing steps**
Test this with ACMS-1107

**Merge requirements**
- [ ] _Major change_, _Minor change_, _Bug_, _Enhancement_, and/or _Chore_ label applied
- [ ] Manual testing by a reviewer

2022-05-23 15:01 UTC, vishalkhode1 requested changes

2022-05-23 15:01 UTC, vishalkhode1 commented on acquia_cms.info.yml
> -  - cohesion_theme
@rajeshreeputra Did we check if this themes are getting installed & enabled after enabling the module ?
cc: @chandan-singh7929

2022-05-26 06:15 UTC, rajeshreeputra commented
This PR can be closed as this is identical with [this](https://github.com/acquia/acquia_cms/pull/1137).

2022-05-26 10:57 UTC, vishalkhode1 commented
Closing this PR as changes are already included in PR #1137

2022-05-26 10:57 UTC, closed without merging