ACMS-1503: Added Acquia DAM Referenced Image temapletes.
acquia/acquia_cms pull request #1298
Opened 2022-10-20 09:52 UTC by rajeshreeputra

**Motivation**
Fixes #ACMS-1503

**Proposed changes**
- Added new view mode 'Referenced Image' for Place and Person content type.
- Updated Article, Event Site studio templates, default view mode.
- Added update hook to update view mode for Article, Event, Person, Place.

**Alternatives considered**
NA

**Testing steps**
- Use this branch
- Install site using acms site:install
- Install ACMS DAM module drush in acquia_cms_dam
- Login into application
- Create node using any content type
- Select DAM media for image in first node
- Select CORE media for image in second node
- Verify images rendering fine on both nodes

**Merge requirements**
- [ ] _Major change_, _Minor change_, _Bug_, _Enhancement_, and/or _Chore_ label applied
- [ ] Manual testing by a reviewer

2022-10-21 06:10 UTC, apathak18 requested changes
Do we a composer.lock file in the PR? @rajeshreeputra

2022-10-21 07:10 UTC, apathak18 commented on modules/acquia_cms_article/acquia_cms_article.install
> +function acquia_cms_article_update_8004() {
Can we create a service class for hook_update logic? and call that service class where we need? @rajeshreeputra 

As I can notice that every content_type.install hook_update having same logic with different variable names.

cc: @vishalkhode1

2022-10-21 11:01 UTC, apathak18 approved these changes
LGTM

2022-10-21 11:22 UTC, rajeshreeputra reviewed
All changes required for ACMS-1389 and ACMS-1503 has been completed, hence moving ahead for review.

2022-10-25 07:18 UTC, vishalkhode1 approved these changes

2022-10-25 07:18 UTC, merged