ACMS-1500: Added modules uninstall validator for site studio packages.
acquia/acquia_cms pull request #1312
Opened 2022-11-02 08:29 UTC by rajeshreeputra

**Motivation**
Fixes #ACMS-1500

**Proposed changes**
Validate site studio packages deleted before uninstalling the module.

**Alternatives considered**
NA

**Testing steps**
- Install site with this code
- Install site studio module import packages
- Now try to uninstall any module having site studio package.
- It should give warning.
- Verify site.

**Merge requirements**
- [ ] _Major change_, _Minor change_, _Bug_, _Enhancement_, and/or _Chore_ label applied
- [ ] Manual testing by a reviewer

2022-11-03 06:07 UTC, deepakmishra2 requested changes
@rajeshreeputra please have a look at the comment.

2022-11-03 06:07 UTC, deepakmishra2 commented on modules/acquia_cms_common/src/AcmsModulesUninstallValidator.php
> +        $config = \Drupal::configFactory()->getEditable($package);
Can we use dependency injection here?

2022-11-03 06:14 UTC, rajeshreeputra commented on modules/acquia_cms_common/src/AcmsModulesUninstallValidator.php
> +        $config = \Drupal::configFactory()->getEditable($package);
done

2022-11-03 06:22 UTC, deepakmishra2 approved these changes
Looks good to me

2022-11-03 06:53 UTC, apathak18 approved these changes
Looks good to me

2022-11-07 11:51 UTC, vishalkhode1 approved these changes

2022-11-07 11:51 UTC, merged