ACMS-1461: Remove tour landing page.
acquia/acquia_cms pull request #1326
Opened 2022-11-22 06:29 UTC by apathak18

**Motivation**

Fixes# ACMS-1461

**Proposed changes**
Removing tour page and its redirect content.

**Testing steps**
From UI, Click on tour menu and it should land you to the get started page.

2022-12-26 08:44 UTC, rajeshreeputra approved these changes
Changes looks good.

2022-12-26 08:51 UTC, rajeshreeputra requested changes
please remove "access acquia cms tour" permission.

2022-12-30 08:28 UTC, chandan-singh7929 commented on modules/acquia_cms_tour/acquia_cms_tour.routing.yml
>  acquia_cms_tour.enabled_modules:
@apathak18 - Lets use route `acquia_cms_tour.tour` instead of `acquia_cms_tour.enabled_modules`.
cc: @vishalkhode1 @vipin-mittal-acquia

2022-12-30 08:32 UTC, chandan-singh7929 commented on modules/acquia_cms_tour/acquia_cms_tour.routing.yml
>  acquia_cms_tour.enabled_modules:
Or more precisely we can create `acquia_cms_tour.wizard`

2023-01-02 11:38 UTC, vishalkhode1 approved these changes

2023-01-02 11:40 UTC, merged