ACMS-1401: CI to test modules upgrade on PR.
acquia/acquia_cms pull request #1474
Opened 2023-03-03 08:51 UTC by deepakmishra2

**Motivation**

Fixes #ACMS-1401

**Proposed changes**
CI to test modules upgrade on PR

**Alternatives considered**

**Testing steps**

**Merge requirements**
- [ ] _Major change_, _Minor change_, _Bug_, _Enhancement_, and/or _Chore_ label applied
- [ ] Manual testing by a reviewer

2023-03-13 11:31 UTC, chandan-singh7929 approved these changes

2023-03-13 11:33 UTC, chandan-singh7929 commented
Changes looks good to me, though I have one observation, when it ran initial there was no pending updates, while adding update hook in one of the module run hook from common modules as well.
<img width="957" alt="Screenshot 2023-03-13 at 4 57 16 PM" src="https://user-images.githubusercontent.com/63041696/224690180-b5e75809-2a3b-4d63-9219-15d6d9bdbaf8.png">
cc @vishalkhode1

2023-03-14 06:00 UTC, apathak18 commented on .github/workflows/acquia_cms_ci.workflow.yml
> +          git config --global user.name "Deepak Mishra"
@deepakmishra2 do we need to add the user config? If we remove 332-333 lines then any issues?

2023-03-14 06:40 UTC, apathak18 approved these changes
LGTM

2023-03-14 10:03 UTC, vishalkhode1 requested changes

2023-03-14 10:03 UTC, vishalkhode1 commented on .github/workflows/acquia_cms_ci.workflow.yml
> +          rm -rf ${ORCA_FIXTURE_DIR}/docroot/modules/contrib
We shouldn't do this. Because ORCA fixture add different modules/libraries and they pin this to specific versions. This will remove this modules.

2023-03-14 10:04 UTC, vishalkhode1 commented
Hi @rajeshreeputra / @deepakmishra2 
I've covered all the above fixes in PR: https://github.com/acquia/acquia_cms/pull/1482. Please review and update the PR accordingly.
cc: @apathak18 / @chandan-singh7929

2023-03-14 10:05 UTC, vishalkhode1 commented
Hi @rajeshreeputra / @deepakmishra2 
I've covered all the above fixes in PR: https://github.com/acquia/acquia_cms/pull/1482. Please review and update the PR accordingly.
cc: @apathak18 / @chandan-singh7929

2023-03-14 11:42 UTC, chandan-singh7929 approved these changes

2023-03-14 11:45 UTC, chandan-singh7929 commented
> Changes looks good to me, though I have one observation, when it ran initial there was no pending updates, while adding update hook in one of the module run hook from common modules as well. <img alt="Screenshot 2023-03-13 at 4 57 16 PM" width="957" src="https://user-images.githubusercontent.com/63041696/224690180-b5e75809-2a3b-4d63-9219-15d6d9bdbaf8.png"> cc @vishalkhode1

Any thoughts on this one.

2023-03-15 04:07 UTC, vishalkhode1 commented
I think this happened because

> Changes looks good to me, though I have one observation, when it ran initial there was no pending updates, while adding update hook in one of the module run hook from common modules as well.

I think this happened, because I recently added this update hooks in `develop` branch in acquia_cms_common module. See this commit: https://github.com/acquia/acquia_cms/commit/fc7d97d94105c194459dbd571d8bd7283b9889be

2023-03-15 04:08 UTC, merged