ACMS-000: add dev branches of acquia_cms_common.
acquia/acquia_cms pull request #1744
Opened 2024-02-20 12:57 UTC by deepakmishra2

**Motivation**

Fixes #NNN

**Proposed changes**

Added dev releases of acquia_cms_common module

**Alternatives considered**

**Testing steps**

**Merge requirements**
- [ ] _Major change_, _Minor change_, _Bug_, _Enhancement_, and/or _Chore_ label applied
- [ ] Manual testing by a reviewer

2024-02-20 13:27 UTC, rajeshreeputra commented on modules/acquia_cms_audio/composer.json
> +        "drupal/acquia_cms_common": "1.x-dev || 2.x-dev || 3.x-dev || 3.1.x-dev || 3.2.x-dev",
```suggestion
        "drupal/acquia_cms_common": "1.x-dev || 2.x-dev || 3.x-dev || 3.1.x-dev || 3.2.x-dev || 3.x-dev",
```

2024-02-20 13:27 UTC, rajeshreeputra commented on modules/acquia_cms_component/composer.json
> +        "drupal/acquia_cms_common": "1.x-dev || 2.x-dev || 3.x-dev || 3.1.x-dev || 3.2.x-dev",
```suggestion
        "drupal/acquia_cms_common": "1.x-dev || 2.x-dev || 3.x-dev || 3.1.x-dev || 3.2.x-dev || 3.x-dev",
```

2024-02-20 13:28 UTC, rajeshreeputra requested changes

2024-02-20 13:42 UTC, chandan-singh7929 commented on modules/acquia_cms_audio/composer.json
> +        "drupal/acquia_cms_common": "1.x-dev || 2.x-dev || 3.x-dev || 3.1.x-dev || 3.2.x-dev",
why we are adding `3.x-dev` twice?

2024-02-20 13:42 UTC, chandan-singh7929 approved these changes
Remove duplicate `3.x-dev` from all the changes, rest looks good

2024-02-20 13:48 UTC, deepakmishra2 commented on modules/acquia_cms_audio/composer.json
> +        "drupal/acquia_cms_common": "1.x-dev || 2.x-dev || 3.x-dev || 3.1.x-dev || 3.2.x-dev",
yes its already there

2024-02-20 13:51 UTC, deepakmishra2 commented
> Remove duplicate `3.x-dev` from all the changes, rest looks good

3.x-dev is added only once , suggested changes by pravin shows its should be added twice

2024-02-21 10:00 UTC, rajeshreeputra approved these changes

2024-02-21 10:10 UTC, apathak18 approved these changes

2024-02-21 10:24 UTC, vishalkhode1 approved these changes

2024-02-21 10:24 UTC, merged