ACMS-3445: Move Opt in and out feature check form in acquia cms common module.
acquia/acquia_cms pull request #1768
Opened 2024-03-11 10:19 UTC by rajeshreeputra

**Motivation**

Fixes #[ACMS-3445](https://acquia.atlassian.net/browse/ACMS-3445)

**Proposed changes**
Move telemetry tour form in Acquia CMS Common.

**Alternatives considered**
NA

**Testing steps**
Follow from ticket.

**Merge requirements**
- [ ] _Major change_, _Minor change_, _Bug_, _Enhancement_, and/or _Chore_ label applied
- [ ] Manual testing by a reviewer

2024-03-11 12:19 UTC, rajeshreeputra commented on modules/acquia_cms_search/src/Plugin/AcquiaCmsTour/AcquiaConnectorForm.php
> -      $form[$module]['opt_in'] = [
Yes.

2024-03-11 12:46 UTC, apathak18 approved these changes

2024-03-11 14:15 UTC, chandan-singh7929 requested changes
I think we should also update, below logic from common if we are moving form, otherwise default value will be false until connector module doesn't get install
```    // Acquia connector check and set telemetry opt-in feature.
    if (in_array('acquia_connector', $modules)) {
      // Set telemetry to be TRUE on install of acquia_connector.
      \Drupal::state()->set('acquia_connector.telemetry.opted', TRUE);
    }
    if (in_array('entity_clone', $modules)) {
      _acquia_cms_common_rewrite_configuration('entity_clone.settings', 'acquia_cms_common');
    }
  }

2024-03-12 12:22 UTC, chandan-singh7929 approved these changes

2024-03-12 12:25 UTC, vishalkhode1 approved these changes

2024-03-12 12:25 UTC, merged